version: '3.4'
services:
  db:
    restart: always
    image: postgres:10-alpine
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - redis:/data
  web:
    build: .
    image: homulilly/mastodon:ruby2.5.1
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    expose:
      - 3000
    depends_on:
      - db
      - redis
    volumes:
      - assets:/mastodon/public/assets
      - packs:/mastodon/public/packs
      - system:/mastodon/public/system
  streaming:
    build: .
    image: homulilly/mastodon:ruby2.5.1
    restart: always
    env_file: .env.production
    command: yarn start
    expose:
      - 4000
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    image: homulilly/mastodon:ruby2.5.1
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -q default -q mailers -q pull -q push -c 10
    depends_on:
      - db
      - redis
    volumes:
      - system:/mastodon/public/system
      - packs:/mastodon/public/packs
  nginx:
    restart: always
    image: nginx:mainline
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/:/etc/nginx/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - ./public:/web/public/:ro
      - assets:/web/assets/:ro
      - packs:/web/packs/:ro
      - system:/web/system/:ro
  netdata:
    image: firehol/netdata
    restart: always
    expose:
      - 19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
volumes:
  assets:
  packs:
  system:
  db:
  redis:
