# Restart webpack-watcher or webpack-dev-server if you make changes here
config: config/webpack
entry: webpack
output: public
node_modules: node_modules
source: app
extensions:
  - .coffee
  - .js
  - .jsx
  - .ts
  - .vue
  - .sass
  - .scss
  - .css
  - .png
  - .svg
  - .gif
  - .jpeg
